services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my-network

  pos-go-redis-limiter:
    build: .
    ports:
      - "8080:8080"
    container_name: pos-go-redis-limiter
    environment:
      - REDIS_ADDR=172.23.0.2:6379
    networks:
      - my-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  my-network:
    driver: bridge